name: intl_phone_number_input
description: A simple and customizable flutter package on International Phone Number Input.
version: 0.2.1
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.4
  libphonenumber: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/flags/
